export { createApp } from './app'
export { DOM_TYPES, h, hFragment, hString, hSlot } from './h'
export { defineComponent } from './component'
export { nextTick } from './scheduler.js'
export { RouterLink, RouterOutlet } from './router-components.js'
export { HashRouter } from './router.js'